// <auto-generated />
using System;
using DevoxTestTask.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DevoxTestTask.DAL.Migrations
{
    [DbContext(typeof(DevoxTestTaskDbContext))]
    partial class DevoxTestTaskDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DevoxTestTask.DAL.Entities.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActivityTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActivityTypeId = 1,
                            Date = new DateTime(2020, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = 3,
                            EmployeeId = 1,
                            Name = "FirstActivity",
                            ProjectId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            ActivityTypeId = 2,
                            Date = new DateTime(2020, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = 5,
                            EmployeeId = 2,
                            Name = "SecondActivity",
                            ProjectId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 3,
                            ActivityTypeId = 1,
                            Date = new DateTime(2020, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Duration = 2,
                            EmployeeId = 1,
                            Name = "ThirdActivity",
                            ProjectId = 2,
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("DevoxTestTask.DAL.Entities.ActivityType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ActivityTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "regular"
                        },
                        new
                        {
                            Id = 2,
                            Name = "overtime"
                        });
                });

            modelBuilder.Entity("DevoxTestTask.DAL.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birthday = new DateTime(2000, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Denis",
                            Sex = "m"
                        },
                        new
                        {
                            Id = 2,
                            Birthday = new DateTime(2001, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Anton",
                            Sex = "m"
                        });
                });

            modelBuilder.Entity("DevoxTestTask.DAL.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateEnd = new DateTime(2020, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2020, 8, 11, 12, 16, 29, 776, DateTimeKind.Local).AddTicks(3028),
                            Name = "First"
                        },
                        new
                        {
                            Id = 2,
                            DateEnd = new DateTime(2020, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2020, 8, 11, 12, 16, 29, 789, DateTimeKind.Local).AddTicks(9238),
                            Name = "Second"
                        },
                        new
                        {
                            Id = 3,
                            DateEnd = new DateTime(2020, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2020, 8, 11, 12, 16, 29, 789, DateTimeKind.Local).AddTicks(9467),
                            Name = "Third"
                        });
                });

            modelBuilder.Entity("DevoxTestTask.DAL.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "engineer"
                        },
                        new
                        {
                            Id = 2,
                            Name = "analyst"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
